CREATE TABLE IF NOT EXISTS telegram_users (
    id               bigint generated by default as identity primary key,
    chat_id          bigint,
    created_at       timestamp(6),
    first_name       varchar(255),
    last_name        varchar(255),
    telegram_user_id bigint,
    updated_at       timestamp(6),
    user_name        varchar(255)
);

CREATE TABLE IF NOT EXISTS lender (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6),
    name       varchar(255),
    updated_at timestamp(6),
    user_id    bigint,
    constraint fk28y2lq1erd7bv8so53pweh7rw
        foreign key (user_id) references telegram_users (id)
);

CREATE TABLE IF NOT EXISTS debt (
    id         bigint generated by default as identity primary key,
    amount     integer,
    created_at timestamp(6),
    updated_at timestamp(6),
    lender_id  bigint,
    constraint fkiromur1tymupejipngr2pjqm9
        foreign key (lender_id) references lender (id)
);
